cat:
	cat Makefile

test:
	python cli_run_composite.py --start 19840501 --end 19840930 --horiz 23 --vert 13

pc:
	./pc_user.py -y 2023 ard_real_short_list.csv

short:
	./pc_user.py -y 2023 short.csv

three:
	./pc_user.py -y 2023 three.csv
